/**
 * Colour provider (#79): every notation of the evidence scan read and written, the round
 * trip, the tree and token paths, files with parse errors and non-colour lists.
 */

import * as assert from 'assert';
import { Color } from 'vscode-languageserver/node';
import { TextDocument } from 'vscode-languageserver-textdocument';
import { CK3Parser } from 'pychivalry-engine';
import {
    COLOR_KEYS,
    ColorNotation,
    ColorProvider,
    ColorStyle,
    hsvToRgb,
    NamedColorTable,
    presentColor,
    readColorList,
    rgbToHsv,
    sameColor,
} from '../../server/lsp/color-provider';
import { testUri } from './helpers/uri';

const GUI_URI = testUri('/mod/gui/window.gui');
const SCRIPT_URI = testUri('/mod/common/culture/cultures/my_cultures.txt');
const NAMED_URI = testUri('/mod/common/named_colors/my_colors.txt');

const STYLE: ColorStyle = { prefixGap: ' ', arity: 3, decimals: 0, padWidth: 0 };

function color(red: number, green: number, blue: number, alpha = 1): Color {
    return { red, green, blue, alpha };
}

function near(actual: Color, expected: Color, epsilon = 0.002): void {
    assert.ok(
        sameColor(actual, expected, epsilon),
        `${JSON.stringify(actual)} != ${JSON.stringify(expected)}`
    );
}

function provider(): ColorProvider {
    const parser = new CK3Parser();
    const named = new NamedColorTable();
    named.addText(
        'colors = {\n\twhite = hsv { 0.08 0.02 0.8 }\n\tred = { 0.8 0.2 0.2 }\n\tbaranis = { 161 67 0 }\n}\n',
        parser
    );
    return new ColorProvider(parser, named);
}

function texts(p: ColorProvider, text: string, uri: string): string[] {
    const document = TextDocument.create(uri, 'ck3', 1, text);
    return p.provideDocumentColors(document).map((c) => document.getText(c.range));
}

describe('Color provider', () => {
    describe('colour keys (generated by tools/color-scan.js)', () => {
        it('holds the keys of the evidence scan and not the DNA palette keys', () => {
            for (const key of ['color', 'color1', 'tintcolor', 'fontcolor', 'map_color']) {
                assert.ok(COLOR_KEYS.has(key), key);
            }
            for (const key of ['hair_color', 'eye_color', 'skin_color', 'position']) {
                assert.ok(!COLOR_KEYS.has(key), key);
            }
        });
    });

    describe('reading each notation', () => {
        it('bare 0..1 lists, three and four values', () => {
            const three = readColorList(undefined, ['0.5', '0.25', '1']);
            assert.strictEqual(three?.notation, 'bare-unit');
            near(three!.color, color(0.5, 0.25, 1));
            const four = readColorList(undefined, ['0', '0', '0', '0.6']);
            assert.strictEqual(four?.notation, 'bare-unit');
            near(four!.color, color(0, 0, 0, 0.6));
        });

        it('bare 0..255 lists, with a 0..1 alpha', () => {
            const three = readColorList(undefined, ['161', '67', '0']);
            assert.strictEqual(three?.notation, 'bare-byte');
            near(three!.color, color(161 / 255, 67 / 255, 0));
            const four = readColorList(undefined, ['200', '20', '0', '0.8']);
            assert.strictEqual(four?.notation, 'bare-byte');
            near(four!.color, color(200 / 255, 20 / 255, 0, 0.8));
        });

        it('rgb { } with 0..255 integers', () => {
            const read = readColorList('rgb', ['201', '166', '138']);
            assert.strictEqual(read?.notation, 'rgb');
            near(read!.color, color(201 / 255, 166 / 255, 138 / 255));
            assert.strictEqual(readColorList('RGB', ['255', '0', '0'])?.notation, 'rgb');
        });

        it('hsv { } with h s v (a) in 0..1', () => {
            const read = readColorList('hsv', ['0', '1', '1']);
            near(read!.color, color(1, 0, 0));
            const alpha = readColorList('hsv', ['0.3333', '1', '1', '0.5']);
            near(alpha!.color, color(0, 1, 0, 0.5), 0.003);
        });

        it('hsv360 { } with h 0..360 and s v 0..100', () => {
            const read = readColorList('hsv360', ['021', '074', '045']);
            assert.strictEqual(read?.notation, 'hsv360');
            const [r, g, b] = hsvToRgb(21 / 360, 0.74, 0.45);
            near(read!.color, color(r, g, b));
        });

        it('hex { rrggbb }', () => {
            const read = readColorList('hex', ['50779b']);
            assert.strictEqual(read?.notation, 'hex');
            near(read!.color, color(0x50 / 255, 0x77 / 255, 0x9b / 255));
        });

        it('leaves values outside the notation ranges alone', () => {
            assert.strictEqual(readColorList(undefined, ['1.77', '1.77', '1.8', '1']), undefined);
            assert.strictEqual(readColorList(undefined, ['0.5', '0.5', '0.5', '2']), undefined);
            assert.strictEqual(readColorList('hsv', ['0.1', '0.2', '12']), undefined);
            assert.strictEqual(readColorList('rgb', ['300', '0', '0']), undefined);
            assert.strictEqual(readColorList('rgb', ['0.5', '0', '0']), undefined);
            assert.strictEqual(readColorList(undefined, ['1', '2']), undefined);
            assert.strictEqual(readColorList(undefined, ['1', '2', '3', '4', '5']), undefined);
            assert.strictEqual(readColorList('hex', ['50779']), undefined);
        });
    });

    describe('writing each notation', () => {
        const red = color(1, 0, 0);
        const cases: [ColorNotation, Partial<ColorStyle>, Color, string][] = [
            ['bare-unit', {}, color(0.5, 0.25, 1), '{ 0.50 0.25 1.00 }'],
            ['bare-unit', { decimals: 1 }, color(0.5, 0.2, 1), '{ 0.5 0.2 1.0 }'],
            ['bare-unit', { arity: 4, decimals: 1 }, red, '{ 1.0 0.0 0.0 1.0 }'],
            ['bare-unit', { decimals: 2 }, color(0, 0, 0, 0.6), '{ 0.00 0.00 0.00 0.60 }'],
            ['bare-byte', {}, color(161 / 255, 67 / 255, 0), '{ 161 67 0 }'],
            [
                'bare-byte',
                { arity: 4, decimals: 1 },
                color(200 / 255, 0.08, 0, 0.8),
                '{ 200 20 0 0.8 }',
            ],
            ['rgb', {}, red, 'rgb { 255 0 0 }'],
            ['rgb', { prefix: 'RGB', prefixGap: '' }, red, 'RGB{ 255 0 0 }'],
            ['hsv', {}, red, 'hsv { 0.00 1.00 1.00 }'],
            ['hsv', { prefixGap: '', decimals: 1 }, color(0, 1, 0, 0.5), 'hsv{ 0.3 1.0 1.0 0.5 }'],
            ['hsv360', { padWidth: 3 }, red, 'hsv360 { 000 100 100 }'],
            ['hex', { prefixGap: '' }, color(0x50 / 255, 0x77 / 255, 0x9b / 255), 'hex{ 50779b }'],
        ];
        for (const [notation, style, c, expected] of cases) {
            it(`${notation} → ${expected}`, () => {
                assert.deepStrictEqual(presentColor(c, notation, { ...STYLE, ...style }), [
                    expected,
                ]);
            });
        }

        it('leaves out notations that cannot hold the colour', () => {
            const translucent = color(1, 0, 0, 0.5);
            assert.deepStrictEqual(presentColor(translucent, 'rgb', STYLE), []);
            assert.deepStrictEqual(presentColor(translucent, 'hsv360', STYLE), []);
            assert.deepStrictEqual(presentColor(translucent, 'hex', STYLE), []);
            // A byte list whose bytes are all 0 or 1 would read back as a 0..1 list.
            assert.deepStrictEqual(presentColor(color(1 / 255, 0, 0), 'bare-byte', STYLE), []);
        });

        it('names the named colours equal to the colour', () => {
            const p = provider();
            assert.deepStrictEqual(presentColor(color(0.8, 0.2, 0.2), 'named', STYLE, p.named), [
                'red',
            ]);
            assert.deepStrictEqual(presentColor(color(0.1, 0.1, 0.1), 'named', STYLE, p.named), []);
        });
    });

    describe('round trip: present, then read, gives the same colour', () => {
        // Deterministic pseudo-random colours.
        let seed = 7;
        const next = (): number => {
            seed = (seed * 1103515245 + 12345) % 2147483648;
            return seed / 2147483648;
        };
        const tolerance: Record<string, number> = {
            'bare-unit': 0.005,
            'bare-byte': 0.5 / 255 + 1e-9,
            rgb: 0.5 / 255 + 1e-9,
            // Two decimals of hue move a channel by up to 6 × 0.005.
            hsv: 0.035,
            // Whole degrees and percentages.
            hsv360: 0.02,
            hex: 0.5 / 255 + 1e-9,
        };
        for (const notation of Object.keys(tolerance) as ColorNotation[]) {
            it(notation, () => {
                for (let i = 0; i < 200; i++) {
                    const alpha = notation === 'bare-unit' || notation === 'hsv' ? next() : 1;
                    const c = color(next(), next(), next(), alpha);
                    for (const text of presentColor(c, notation, STYLE)) {
                        const m = /^([A-Za-z0-9]*)\s*\{\s*(.*?)\s*\}$/.exec(text);
                        assert.ok(m, text);
                        const read = readColorList(
                            m[1] === '' ? undefined : m[1],
                            m[2].split(/\s+/)
                        );
                        assert.ok(read, `${text} reads back`);
                        assert.strictEqual(read.notation, notation, text);
                        near(read.color, c, tolerance[notation]);
                    }
                }
            });
        }

        it('rgbToHsv inverts hsvToRgb', () => {
            for (let i = 0; i < 200; i++) {
                const [r, g, b] = [next(), next(), next()];
                const [h, s, v] = rgbToHsv(r, g, b);
                const [r2, g2, b2] = hsvToRgb(h, s, v);
                near(color(r2, g2, b2), color(r, g, b), 1e-9);
            }
        });
    });

    describe('finding values', () => {
        it('reads a clean script file from the tree', () => {
            const p = provider();
            const text = [
                'my_culture = {',
                '\tcolor = { 0.8 0.2 0.2 }',
                '\tcoa = { color1 = white color2 = rgb { 201 166 138 } }',
                '\tlanded = { color = { 161 67 0 } }',
                '\tlevels_min = hsv{ 0 0 0 }',
                '}',
                '',
            ].join('\n');
            const scan = p.findColors(text, SCRIPT_URI);
            assert.strictEqual(scan.path, 'tree');
            assert.deepStrictEqual(
                scan.values.map((v) => v.notation),
                ['bare-unit', 'named', 'rgb', 'bare-byte', 'hsv']
            );
            assert.deepStrictEqual(texts(p, text, SCRIPT_URI), [
                '{ 0.8 0.2 0.2 }',
                'white',
                'rgb { 201 166 138 }',
                '{ 161 67 0 }',
                'hsv{ 0 0 0 }',
            ]);
        });

        it('reads a GUI file with parse errors from the tokens', () => {
            const p = provider();
            const text = [
                'types Window {',
                '\ttype my_window = window {',
                '\t\ttintcolor = { 200 20 0 0.8 }',
                '\t\ttext = "[GetName]" # color = { 1 0 0 }',
                '\t\tfontcolor = { 0.5 0.5 0.5 1 }',
                '\t\tposition = { 10 20 30 }',
                '\t}',
                '}',
                '',
            ].join('\n');
            const scan = p.findColors(text, GUI_URI);
            assert.strictEqual(scan.path, 'scan');
            assert.deepStrictEqual(texts(p, text, GUI_URI), [
                '{ 200 20 0 0.8 }',
                '{ 0.5 0.5 0.5 1 }',
            ]);
        });

        it('reads hex { } and named-colour definitions', () => {
            const p = provider();
            assert.deepStrictEqual(
                texts(p, 'env = {\n\tfog_color = hex{ 50779b }\n}\n', SCRIPT_URI),
                ['hex{ 50779b }']
            );
            const named =
                'colors = {\n\tenglish = { 0.8 0.2 0.2 }\n\twelsh = hsv{ 0.68 0.6 0.72 }\n}\n';
            assert.deepStrictEqual(texts(p, named, NAMED_URI), [
                '{ 0.8 0.2 0.2 }',
                'hsv{ 0.68 0.6 0.72 }',
            ]);
            // The same entries outside a named-colour file are not colour keys.
            assert.deepStrictEqual(texts(p, named, SCRIPT_URI), ['hsv{ 0.68 0.6 0.72 }']);
        });

        it('leaves non-colour lists and out-of-range values alone', () => {
            const p = provider();
            const text = [
                'thing = {',
                '\tposition = { 1 2 3 }',
                '\thair_color = { 109 249 109 249 }',
                '\tcolor = { 1.77 1.77 1.80 1 }',
                '\tsun_color = hsv{ 0.1 0.2 12 }',
                '\tcolor = { a b c }',
                '\tcolor1 = not_a_named_color',
                '}',
                '',
            ].join('\n');
            assert.deepStrictEqual(texts(p, text, SCRIPT_URI), []);
            assert.deepStrictEqual(p.fromTokens(text, SCRIPT_URI), []);
        });

        it('the tree and token paths agree on a clean file', () => {
            const p = provider();
            const text = [
                'a = { color = { 0.1 0.2 0.3 } map_color = rgb { 1 2 3 } }',
                'b = { color1 = red color2 = baranis tintcolor = { 0 0 0 0.5 } }',
                'c = { list = { rgb { 255 0 0 } hsv { 0 1 1 } } }',
                '',
            ].join('\n');
            const tree = p.findColors(text, SCRIPT_URI);
            assert.strictEqual(tree.path, 'tree');
            const tokens = p.fromTokens(text, SCRIPT_URI);
            assert.strictEqual(tokens.length, 7);
            assert.deepStrictEqual(
                tokens.map((v) => [v.notation, v.range]),
                tree.values.map((v) => [v.notation, v.range])
            );
        });

        it('reads CRLF files with the same ranges', () => {
            const p = provider();
            const text = 'a = {\r\n\tcolor = { 0.1 0.2 0.3 }\r\n}\r\n';
            const [value] = p.findColors(text, SCRIPT_URI).values;
            assert.deepStrictEqual(value.range, {
                start: { line: 1, character: 9 },
                end: { line: 1, character: 24 },
            });
        });
    });

    describe('presentations', () => {
        it('the value notation first, written like the value, then the alternatives', () => {
            const p = provider();
            const text = 'a = {\n\tcolor = hsv{ 0.10 0.20 0.30 }\n}\n';
            const document = TextDocument.create(SCRIPT_URI, 'ck3', 1, text);
            const [info] = p.provideDocumentColors(document);
            const labels = p
                .provideColorPresentations(document, color(1, 0, 0), info.range)
                .map((x) => x.label);
            assert.deepStrictEqual(labels, [
                'hsv{ 0.00 1.00 1.00 }',
                '{ 255 0 0 }',
                '{ 1.00 0.00 0.00 }',
                'rgb{ 255 0 0 }',
            ]);
        });

        it('keeps alpha and offers only notations that hold it', () => {
            const p = provider();
            const text = 'w = {\n\ttintcolor = { 0.5 0.5 0.5 0.8 }\n}\n';
            const document = TextDocument.create(GUI_URI, 'ck3', 1, text);
            const [info] = p.provideDocumentColors(document);
            const presentations = p.provideColorPresentations(
                document,
                color(0, 0, 1, 0.4),
                info.range
            );
            assert.deepStrictEqual(
                presentations.map((x) => x.label),
                ['{ 0.0 0.0 1.0 0.4 }']
            );
            assert.deepStrictEqual(presentations[0].textEdit?.range, info.range);
        });

        it('a named value offers the matching names first', () => {
            const p = provider();
            const text = 'coa = {\n\tcolor1 = white\n}\n';
            const document = TextDocument.create(SCRIPT_URI, 'ck3', 1, text);
            const [info] = p.provideDocumentColors(document);
            const labels = p
                .provideColorPresentations(document, color(0.8, 0.2, 0.2), info.range)
                .map((x) => x.label);
            assert.strictEqual(labels[0], 'red');
            assert.ok(labels.includes('rgb { 204 51 51 }'));
        });
    });
});
