/**
 * Color Provider - colour swatches and a colour picker for CK3 colour values (#79).
 *
 * The notations, their value ranges and the keys a bare `{ … }` list is a colour under come
 * from the evidence scan of the base game and the real-mod corpus (tools/color-scan.js,
 * Documentation/developer-guide/color-notations.md); the key list is its generated output
 * (server/data/color-keys.json). Implemented notations and ranges:
 *
 * | Notation    | Written as                 | Range                                          |
 * | ----------- | -------------------------- | ---------------------------------------------- |
 * | `bare-unit` | `{ r g b }`, `{ r g b a }` | r g b a in 0..1                                |
 * | `bare-byte` | `{ r g b }`, `{ r g b a }` | r g b integers 0..255 (one above 1), a in 0..1 |
 * | `rgb`       | `rgb { r g b }`            | integers 0..255                                |
 * | `hsv`       | `hsv { h s v }`, `+ a`     | h s v a in 0..1                                |
 * | `hsv360`    | `hsv360 { h s v }`         | h 0..360, s v 0..100                           |
 * | `hex`       | `hex { rrggbb }`           | six hexadecimal digits                         |
 * | `named`     | `color1 = white`           | a colour of a `common/named_colors` file       |
 *
 * Values outside these ranges (HSV light intensities above 1, overbright lists) get no
 * swatch: the picker could not give them back. A prefixed value (`rgb`, `hsv`, `hsv360`,
 * `hex`) is a colour under any key; a bare list or a name only under a colour key, and a
 * bare list also as an entry of a named-colour file's `colors` block.
 *
 * Two paths find the values: the engine's tree when the file parses without errors, and a
 * scan of the engine lexer's tokens when it does not (GUI files use syntax the engine
 * parser reports errors on). Both read the same notations.
 */

import { Color, ColorInformation, ColorPresentation, Range } from 'vscode-languageserver/node';
import { TextDocument } from 'vscode-languageserver-textdocument';
import {
    ASTNode,
    CK3Parser,
    Lexer,
    NodeType,
    ParsedDocument,
    Token,
    TokenType,
} from 'pychivalry-engine';
import colorKeyData from '../data/color-keys.json';

export type ColorNotation = 'bare-unit' | 'bare-byte' | 'rgb' | 'hsv' | 'hsv360' | 'hex' | 'named';

/** How a colour value was written: what a presentation keeps of it. */
export interface ColorStyle {
    /** The prefix as written (`rgb`, `HSV`, `hex`), for prefixed notations. */
    prefix?: string;
    /** What stands between the prefix and `{` (`''` for `hsv{`, `' '` for `hsv {`). */
    prefixGap: string;
    /** Number of components written (3 or 4). */
    arity: number;
    /** Decimal places of the fractional components (0 when none had any). */
    decimals: number;
    /** Zero-padded width of integer components (`021` → 3), 0 when unpadded. */
    padWidth: number;
}

export interface ColorValue {
    notation: ColorNotation;
    range: Range;
    color: Color;
    style: ColorStyle;
    /** The colour's name, for the `named` notation. */
    name?: string;
}

export interface ColorScan {
    values: ColorValue[];
    /** `tree`: read from the engine's AST; `scan`: from the lexer tokens (parse errors). */
    path: 'tree' | 'scan';
}

/** Keys a bare list or a name is a colour under (generated by tools/color-scan.js). */
export const COLOR_KEYS: ReadonlySet<string> = new Set(colorKeyData.keys.map((k) => k.key));

const PREFIX_NOTATIONS: Readonly<Record<string, ColorNotation>> = {
    rgb: 'rgb',
    hsv: 'hsv',
    hsv360: 'hsv360',
    hex: 'hex',
};

const HEX_RE = /^[0-9a-fA-F]{6}$/;
const NUMBER_RE = /^-?(\d+(\.\d+)?|\.\d+)$/;
const INTEGER_RE = /^\d+$/;
/** Half a step of the coarsest notation (one 255th): two colours this close are equal. */
const COLOR_EPSILON = 0.5 / 255;

function prefixNotation(word: string): ColorNotation | undefined {
    return PREFIX_NOTATIONS[word.toLowerCase()];
}

function within(value: number, low: number, high: number): boolean {
    return value >= low && value <= high;
}

// ── colour arithmetic ───────────────────────────────────────────────────────

export function hsvToRgb(h: number, s: number, v: number): [number, number, number] {
    const hue = (((h % 1) + 1) % 1) * 6;
    const i = Math.floor(hue);
    const f = hue - i;
    const p = v * (1 - s);
    const q = v * (1 - s * f);
    const t = v * (1 - s * (1 - f));
    switch (i) {
        case 0:
            return [v, t, p];
        case 1:
            return [q, v, p];
        case 2:
            return [p, v, t];
        case 3:
            return [p, q, v];
        case 4:
            return [t, p, v];
        default:
            return [v, p, q];
    }
}

export function rgbToHsv(r: number, g: number, b: number): [number, number, number] {
    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    const d = max - min;
    let h = 0;
    if (d > 0) {
        if (max === r) {
            h = ((g - b) / d) % 6;
        } else if (max === g) {
            h = (b - r) / d + 2;
        } else {
            h = (r - g) / d + 4;
        }
        h /= 6;
        if (h < 0) {
            h += 1;
        }
    }
    return [h, max === 0 ? 0 : d / max, max];
}

function rgba(r: number, g: number, b: number, a = 1): Color {
    return { red: r, green: g, blue: b, alpha: a };
}

export function sameColor(a: Color, b: Color, epsilon = COLOR_EPSILON): boolean {
    return (
        Math.abs(a.red - b.red) <= epsilon &&
        Math.abs(a.green - b.green) <= epsilon &&
        Math.abs(a.blue - b.blue) <= epsilon &&
        Math.abs(a.alpha - b.alpha) <= epsilon
    );
}

// ── reading values ──────────────────────────────────────────────────────────

function styleOf(raw: string[], prefix: string | undefined, prefixGap: string): ColorStyle {
    let decimals = 0;
    let padWidth = 0;
    for (const value of raw) {
        const dot = value.indexOf('.');
        if (dot >= 0) {
            decimals = Math.max(decimals, value.length - dot - 1);
        } else if (value.length > 1 && value.startsWith('0')) {
            padWidth = Math.max(padWidth, value.length);
        }
    }
    return { prefix, prefixGap, arity: raw.length, decimals, padWidth };
}

/**
 * The colour of a value list: `notation` is the prefix's notation, or undefined for a bare
 * list (classified bare-unit or bare-byte by its values). Undefined when out of range.
 */
export function readColorList(
    prefix: string | undefined,
    raw: string[]
): { notation: ColorNotation; color: Color } | undefined {
    const notation = prefix === undefined ? undefined : prefixNotation(prefix);
    if (prefix !== undefined && notation === undefined) {
        return undefined;
    }
    if (notation === 'hex') {
        if (raw.length !== 1 || !HEX_RE.test(raw[0])) {
            return undefined;
        }
        const n = parseInt(raw[0], 16);
        return {
            notation,
            color: rgba(((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255),
        };
    }
    if (!raw.every((v) => NUMBER_RE.test(v))) {
        return undefined;
    }
    const v = raw.map(Number);
    switch (notation) {
        case 'rgb':
            if (
                raw.length === 3 &&
                raw.every((x) => INTEGER_RE.test(x)) &&
                v.every((x) => x <= 255)
            ) {
                return { notation, color: rgba(v[0] / 255, v[1] / 255, v[2] / 255) };
            }
            return undefined;
        case 'hsv':
            if ((raw.length === 3 || raw.length === 4) && v.every((x) => within(x, 0, 1))) {
                const [r, g, b] = hsvToRgb(v[0], v[1], v[2]);
                return { notation, color: rgba(r, g, b, v[3] ?? 1) };
            }
            return undefined;
        case 'hsv360':
            if (
                raw.length === 3 &&
                within(v[0], 0, 360) &&
                within(v[1], 0, 100) &&
                within(v[2], 0, 100)
            ) {
                const [r, g, b] = hsvToRgb(v[0] / 360, v[1] / 100, v[2] / 100);
                return { notation, color: rgba(r, g, b) };
            }
            return undefined;
        default:
            break;
    }
    // A bare list.
    if (raw.length !== 3 && raw.length !== 4) {
        return undefined;
    }
    const alpha = v[3] ?? 1;
    if (!within(alpha, 0, 1)) {
        return undefined;
    }
    if (v.slice(0, 3).every((x) => within(x, 0, 1))) {
        return { notation: 'bare-unit', color: rgba(v[0], v[1], v[2], alpha) };
    }
    if (raw.slice(0, 3).every((x) => INTEGER_RE.test(x)) && v.slice(0, 3).every((x) => x <= 255)) {
        return { notation: 'bare-byte', color: rgba(v[0] / 255, v[1] / 255, v[2] / 255, alpha) };
    }
    return undefined;
}

// ── writing values ──────────────────────────────────────────────────────────

function fixed(value: number, decimals: number): string {
    return value.toFixed(decimals);
}

function padded(value: number, width: number): string {
    return String(value).padStart(width, '0');
}

function opaque(color: Color): boolean {
    return Math.abs(color.alpha - 1) <= COLOR_EPSILON;
}

/**
 * The text of `color` in `notation`, written like `style` (prefix spelling, prefix gap,
 * component count, decimal places, zero padding). Undefined when the notation cannot hold
 * the colour (alpha below 1 in a notation without alpha, a byte list that would read back
 * as a 0..1 list).
 */
export function presentColor(
    color: Color,
    notation: ColorNotation,
    style: ColorStyle,
    named?: NamedColorTable
): string[] {
    const sameNotation = (p: string): string =>
        style.prefix !== undefined && style.prefix.toLowerCase() === p ? style.prefix : p;
    const gap = style.prefixGap;
    const decimals = style.decimals > 0 ? style.decimals : 2;
    const withAlpha = style.arity === 4 || !opaque(color);
    const byte = (x: number): number => Math.round(x * 255);
    switch (notation) {
        case 'bare-unit': {
            const parts = [color.red, color.green, color.blue].map((x) => fixed(x, decimals));
            if (withAlpha) {
                parts.push(fixed(color.alpha, decimals));
            }
            return [`{ ${parts.join(' ')} }`];
        }
        case 'bare-byte': {
            const rgb = [color.red, color.green, color.blue].map(byte);
            if (rgb.every((x) => x <= 1)) {
                return []; // it would read back as a 0..1 list
            }
            const parts = rgb.map((x) => padded(x, style.padWidth));
            if (withAlpha) {
                parts.push(fixed(color.alpha, style.decimals > 0 ? style.decimals : 1));
            }
            return [`{ ${parts.join(' ')} }`];
        }
        case 'rgb': {
            if (!opaque(color)) {
                return [];
            }
            const parts = [color.red, color.green, color.blue].map((x) =>
                padded(byte(x), style.padWidth)
            );
            return [`${sameNotation('rgb')}${gap}{ ${parts.join(' ')} }`];
        }
        case 'hsv': {
            const parts = rgbToHsv(color.red, color.green, color.blue).map((x) =>
                fixed(x, decimals)
            );
            if (withAlpha) {
                parts.push(fixed(color.alpha, decimals));
            }
            return [`${sameNotation('hsv')}${gap}{ ${parts.join(' ')} }`];
        }
        case 'hsv360': {
            if (!opaque(color)) {
                return [];
            }
            const [h, s, v] = rgbToHsv(color.red, color.green, color.blue);
            const parts = [Math.round(h * 360) % 360, Math.round(s * 100), Math.round(v * 100)].map(
                (x) => padded(x, style.padWidth)
            );
            return [`${sameNotation('hsv360')}${gap}{ ${parts.join(' ')} }`];
        }
        case 'hex': {
            if (!opaque(color)) {
                return [];
            }
            const digits = [color.red, color.green, color.blue]
                .map((x) => byte(x).toString(16).padStart(2, '0'))
                .join('');
            return [`${sameNotation('hex')}${gap}{ ${digits} }`];
        }
        case 'named':
            return named ? named.namesOf(color) : [];
    }
}

/** Alternatives offered after the value's own notation, by file kind (evidence order). */
function alternativesFor(uri: string): ColorNotation[] {
    // GUI files write colours only as bare 0..1 lists in the evidence (no prefixes at all).
    if (/\.gui$/i.test(uri)) {
        return ['bare-unit'];
    }
    // Script, gfx and asset files: bare byte lists, bare 0..1 lists, hsv, rgb (by count).
    return ['bare-byte', 'bare-unit', 'hsv', 'rgb'];
}

// ── named colours ───────────────────────────────────────────────────────────

/** The colours of the `common/named_colors` files of the workspace and the base game. */
export class NamedColorTable {
    private colors = new Map<string, Color>();

    public get size(): number {
        return this.colors.size;
    }

    public get(name: string): Color | undefined {
        return this.colors.get(name);
    }

    /** Names whose colour is `color` (within a 255th), in definition order. */
    public namesOf(color: Color): string[] {
        const names: string[] = [];
        for (const [name, c] of this.colors) {
            if (sameColor(c, color)) {
                names.push(name);
            }
        }
        return names;
    }

    /** Add the definitions of one named-colour file's text (later files override). */
    public addText(text: string, parser: Pick<CK3Parser, 'parse'>): number {
        let added = 0;
        for (const top of parser.parse(text).ast.children ?? []) {
            if (top.type !== NodeType.BLOCK || top.key !== 'colors') {
                continue;
            }
            for (const entry of top.children ?? []) {
                if (entry.type !== NodeType.LIST || entry.key === undefined) {
                    continue;
                }
                const prefix = entry.valueKind === 'color' ? String(entry.value) : undefined;
                const read = readColorList(prefix, listRaw(entry));
                if (read) {
                    this.colors.set(entry.key, read.color);
                    added++;
                }
            }
        }
        return added;
    }

    /**
     * Replace the table with the definitions of named-colour files' texts, in load order
     * (base game first: later texts override earlier ones; server/data/named-colors.ts
     * reads them). Returns the number of names.
     */
    public load(texts: string[], parser: Pick<CK3Parser, 'parse'>): number {
        this.colors = new Map();
        for (const text of texts) {
            this.addText(text, parser);
        }
        return this.colors.size;
    }
}

/** The values of a LIST node as written (number literals keep their spelling). */
function listRaw(node: ASTNode): string[] {
    const raw: string[] = [];
    for (const child of node.children ?? []) {
        if (child.type === NodeType.COMMENT) {
            continue;
        }
        raw.push(child.raw ?? String(child.value));
    }
    return raw;
}

// ── finding values ──────────────────────────────────────────────────────────

function isNamedColorFile(uri: string): boolean {
    return /\/common\/named_colors\//i.test(decodeURIComponent(uri).replace(/\\/g, '/'));
}

/** Line start offsets of a text, for position ↔ offset conversion. */
function lineStarts(text: string): number[] {
    const starts = [0];
    for (let i = 0; i < text.length; i++) {
        if (text.charCodeAt(i) === 10) {
            starts.push(i + 1);
        }
    }
    return starts;
}

export class ColorProvider {
    constructor(
        private parser: { parse(text: string): ParsedDocument },
        public readonly named: NamedColorTable = new NamedColorTable()
    ) {}

    public provideDocumentColors(document: TextDocument): ColorInformation[] {
        return this.findColors(document.getText(), document.uri).values.map((v) => ({
            range: v.range,
            color: v.color,
        }));
    }

    /**
     * Presentations of `color` for the value at `range`: its own notation first (written
     * the way the value was), then the alternatives of the file kind. Notations that cannot
     * hold the colour (alpha) are left out.
     */
    public provideColorPresentations(
        document: TextDocument,
        color: Color,
        range: Range
    ): ColorPresentation[] {
        const found = this.findColors(document.getText(), document.uri).values.find(
            (v) =>
                v.range.start.line === range.start.line &&
                v.range.start.character === range.start.character &&
                v.range.end.line === range.end.line &&
                v.range.end.character === range.end.character
        );
        const style: ColorStyle = found?.style ?? {
            prefixGap: ' ',
            arity: 3,
            decimals: 0,
            padWidth: 0,
        };
        const order: ColorNotation[] = [];
        if (found) {
            order.push(found.notation);
        }
        for (const n of alternativesFor(document.uri)) {
            if (!order.includes(n)) {
                order.push(n);
            }
        }
        const texts: string[] = [];
        for (const notation of order) {
            // Alternatives are written with the prefix spacing of the value but their own
            // decimals and padding.
            const s: ColorStyle =
                found && notation === found.notation
                    ? style
                    : { ...style, prefix: undefined, decimals: 0, padWidth: 0 };
            for (const text of presentColor(color, notation, s, this.named)) {
                if (!texts.includes(text)) {
                    texts.push(text);
                }
            }
        }
        return texts.map((label) => ({ label, textEdit: { range, newText: label } }));
    }

    /** Every colour value of a text, from the tree when it parses, from the tokens if not. */
    public findColors(text: string, uri: string): ColorScan {
        const parsed = this.parser.parse(text);
        if (parsed.errors.some((e) => e.severity === 'error')) {
            return { values: this.fromTokens(text, uri), path: 'scan' };
        }
        return { values: this.fromTree(text, parsed.ast, uri), path: 'tree' };
    }

    // ── the tree path ───────────────────────────────────────────────────────

    public fromTree(text: string, ast: ASTNode, uri: string): ColorValue[] {
        const starts = lineStarts(text);
        const offset = (p: { line: number; character: number }): number =>
            (starts[p.line] ?? text.length) + p.character;
        const positionAt = (o: number): { line: number; character: number } => {
            let low = 0;
            let high = starts.length - 1;
            while (low < high) {
                const mid = (low + high + 1) >> 1;
                if (starts[mid] <= o) {
                    low = mid;
                } else {
                    high = mid - 1;
                }
            }
            return { line: low, character: o - starts[low] };
        };
        /** The '{' after a key (skipping the operator, white space and comments). */
        const braceAfter = (from: number): number | undefined => {
            for (let i = from; i < text.length; i++) {
                const c = text[i];
                if (c === '#') {
                    while (i < text.length && text[i] !== '\n') {
                        i++;
                    }
                    continue;
                }
                if (c === '{') {
                    return i;
                }
                if (!/[\s=<>?!]/.test(c)) {
                    return undefined;
                }
            }
            return undefined;
        };
        /** The range from `start` to just after the closing brace of `node`. */
        const toClose = (start: number, node: ASTNode): Range | undefined => {
            const close = offset(node.range.end);
            if (text[close] !== '}') {
                return undefined;
            }
            return { start: positionAt(start), end: positionAt(close + 1) };
        };
        const namedFile = isNamedColorFile(uri);
        const out: ColorValue[] = [];

        const visit = (nodes: ASTNode[], parentKey: string | undefined, depth: number): void => {
            for (let i = 0; i < nodes.length; i++) {
                const node = nodes[i];
                if (node.type === NodeType.LIST && node.valueKind === 'color') {
                    // `rgb { … }`, `hsv { … }`, `hsv360 { … }` under any key or in a list.
                    const prefix = String(node.value);
                    const start = offset(node.valueRange?.start ?? node.range.start);
                    const raw = listRaw(node);
                    const read = readColorList(prefix, raw);
                    const range = toClose(start, node);
                    const brace = text.indexOf('{', start + prefix.length);
                    if (read && range && brace >= 0) {
                        out.push({
                            notation: read.notation,
                            range,
                            color: read.color,
                            style: styleOf(raw, prefix, text.slice(start + prefix.length, brace)),
                        });
                    }
                    continue;
                }
                if (node.type === NodeType.LIST) {
                    const definition = namedFile && depth === 1 && parentKey === 'colors';
                    if (
                        node.key !== undefined &&
                        node.keyRange &&
                        (COLOR_KEYS.has(node.key) || definition)
                    ) {
                        const raw = listRaw(node);
                        const read = readColorList(undefined, raw);
                        const brace = braceAfter(offset(node.keyRange.end));
                        const range = brace === undefined ? undefined : toClose(brace, node);
                        if (read && range) {
                            out.push({
                                notation: read.notation,
                                range,
                                color: read.color,
                                style: styleOf(raw, undefined, ''),
                            });
                            continue;
                        }
                    }
                    visit(node.children ?? [], node.key, depth + 1);
                    continue;
                }
                if (
                    node.type === NodeType.ASSIGNMENT &&
                    typeof node.value === 'string' &&
                    node.value.toLowerCase() === 'hex' &&
                    node.valueRange
                ) {
                    // `hex { rrggbb }`: the engine reads the prefix and the list apart.
                    const next = nodes[i + 1];
                    if (next && next.type === NodeType.LIST && next.key === undefined) {
                        const raw = listRaw(next);
                        const read = readColorList(node.value, raw);
                        const start = offset(node.valueRange.start);
                        const range = toClose(start, next);
                        const brace = offset(next.range.start);
                        if (read && range && text[brace] === '{') {
                            out.push({
                                notation: 'hex',
                                range,
                                color: read.color,
                                style: styleOf(
                                    [],
                                    node.value,
                                    text.slice(start + node.value.length, brace)
                                ),
                            });
                            i++;
                            continue;
                        }
                    }
                }
                if (
                    node.type === NodeType.ASSIGNMENT &&
                    node.key !== undefined &&
                    COLOR_KEYS.has(node.key) &&
                    typeof node.value === 'string' &&
                    node.valueKind !== 'number' &&
                    node.valueRange
                ) {
                    const color = this.named.get(node.value);
                    if (color) {
                        out.push({
                            notation: 'named',
                            range: node.valueRange,
                            color,
                            name: node.value,
                            style: { prefixGap: ' ', arity: 3, decimals: 0, padWidth: 0 },
                        });
                    }
                    continue;
                }
                if (node.type === NodeType.BLOCK) {
                    visit(node.children ?? [], node.key, depth + 1);
                }
            }
        };
        visit(ast.children ?? [], undefined, 0);
        return out;
    }

    // ── the token path ──────────────────────────────────────────────────────

    public fromTokens(text: string, uri: string): ColorValue[] {
        const tokens: Token[] = new Lexer()
            .tokenize(text)
            .tokens.filter((t) => t.type !== TokenType.NEWLINE && t.type !== TokenType.COMMENT);
        const namedFile = isNamedColorFile(uri);
        const out: ColorValue[] = [];
        const stack: (string | undefined)[] = [];
        let pendingKey: string | undefined;
        const isWord = (t: Token | undefined): boolean =>
            t !== undefined &&
            (t.type === TokenType.IDENTIFIER ||
                t.type === TokenType.NUMBER ||
                t.type === TokenType.SCOPE_CHAIN);
        /** The word items of `{ … }` at index `at`, and the index of its '}'. */
        const list = (at: number): { raw: string[]; close: number } | undefined => {
            if (tokens[at]?.type !== TokenType.LEFT_BRACE) {
                return undefined;
            }
            const raw: string[] = [];
            let j = at + 1;
            while (isWord(tokens[j])) {
                raw.push(tokens[j].value);
                j++;
            }
            return tokens[j]?.type === TokenType.RIGHT_BRACE ? { raw, close: j } : undefined;
        };
        const gap = (a: Token, b: Token): string =>
            a.range.end.line === b.range.start.line
                ? ' '.repeat(b.range.start.character - a.range.end.character)
                : ' ';

        for (let i = 0; i < tokens.length; i++) {
            const t = tokens[i];
            if (t.type === TokenType.LEFT_BRACE) {
                stack.push(pendingKey);
                pendingKey = undefined;
                continue;
            }
            if (t.type === TokenType.RIGHT_BRACE) {
                stack.pop();
                continue;
            }
            // A prefixed value anywhere: `rgb { … }`.
            if (t.type === TokenType.IDENTIFIER && prefixNotation(t.value) !== undefined) {
                const items = list(i + 1);
                if (items) {
                    const read = readColorList(t.value, items.raw);
                    if (read) {
                        out.push({
                            notation: read.notation,
                            range: { start: t.range.start, end: tokens[items.close].range.end },
                            color: read.color,
                            style: styleOf(
                                read.notation === 'hex' ? [] : items.raw,
                                t.value,
                                gap(t, tokens[i + 1])
                            ),
                        });
                        i = items.close;
                        continue;
                    }
                }
            }
            const op = tokens[i + 1];
            const value = tokens[i + 2];
            if (
                !isWord(t) ||
                op === undefined ||
                !(op.type === TokenType.EQUALS || op.type === TokenType.NULL_SAFE_EQUALS) ||
                value === undefined
            ) {
                continue;
            }
            const parent = stack.length > 0 ? stack[stack.length - 1] : undefined;
            const definition = namedFile && stack.length === 1 && parent === 'colors';
            if (value.type === TokenType.LEFT_BRACE) {
                const items = list(i + 2);
                if (items && (COLOR_KEYS.has(t.value) || definition)) {
                    const read = readColorList(undefined, items.raw);
                    if (read) {
                        out.push({
                            notation: read.notation,
                            range: { start: value.range.start, end: tokens[items.close].range.end },
                            color: read.color,
                            style: styleOf(items.raw, undefined, ''),
                        });
                        i = items.close;
                        continue;
                    }
                }
                // A block opens: its key is the parent of what follows.
                pendingKey = t.value;
                i += 1;
                continue;
            }
            if (
                COLOR_KEYS.has(t.value) &&
                (value.type === TokenType.IDENTIFIER || value.type === TokenType.STRING) &&
                prefixNotation(value.value) === undefined
            ) {
                const color = this.named.get(value.value);
                if (color) {
                    out.push({
                        notation: 'named',
                        range: value.range,
                        color,
                        name: value.value,
                        style: { prefixGap: ' ', arity: 3, decimals: 0, padWidth: 0 },
                    });
                    i += 2;
                }
            }
        }
        return out;
    }
}
