/**
 * Generate Documentation/user-guide/diagnostics/ from the diagnostics sources of truth:
 *
 *   - the error catalogue of the spec package bundled by the engine (pychivalry-engine,
 *     `spec.data.errors`): one page per catalogue category, each entry marked when the
 *     engine itself reports it;
 *   - the engine's package-local `PYCH-` messages (`PYCH_MESSAGES`);
 *   - data/diagnostics.yaml, the codes of the extension's plug-ins: one page per plug-in.
 *
 * Which catalogue ids the engine reports, and at which stage and severity, is read from the
 * engine's sources (packages/engine/src), so the pages follow the code.
 *
 * Usage (from the repository root, after `npm run build`):
 *   npm run docs:diagnostics          write the pages
 *   npm run docs:diagnostics:check    fail (exit 1) when the pages are out of date, when a
 *                                     plug-in emits a code data/diagnostics.yaml lacks, or
 *                                     when the file lists a code no plug-in emits
 *
 * Dependencies: the workspace's engine package and js-yaml (both already installed); no
 * new packages.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { defaultSpec, PYCH_MESSAGES } from 'pychivalry-engine';

const ROOT = path.resolve(__dirname, '..', '..');
const OUT_DIR = path.join(ROOT, 'Documentation', 'user-guide', 'diagnostics');
const ENGINE_SRC = path.join(ROOT, 'packages', 'engine', 'src');
const PLUGIN_CATALOGUE = path.join(ROOT, 'data', 'diagnostics.yaml');
const PLUGIN_SOURCES = [
    path.join(ROOT, 'vscode-extension', 'src', 'server', 'ck3', 'validation'),
    path.join(ROOT, 'vscode-extension', 'src', 'server', 'ck3', 'localization', 'validator.ts'),
];

const GENERATED_NOTE =
    '<!-- Generated by tools/gen-diagnostics-docs.ts; do not edit. Run `npm run docs:diagnostics`. -->';

type Severity = 'error' | 'warning' | 'information' | 'hint';
const SEVERITIES: readonly Severity[] = ['error', 'warning', 'information', 'hint'];

interface CatalogueEntry {
    id: string;
    category: string;
    text: string;
    since: string;
    note: string;
}

interface EngineUse {
    stage: string;
    severity: Severity;
}

interface PluginInfo {
    source: string;
    description: string;
}

interface PluginCode {
    code: string;
    plugins: string[];
    severity: Severity;
    message: string;
}

// ---------------------------------------------------------------------------
// Sources
// ---------------------------------------------------------------------------

function walk(dir: string, out: string[] = []): string[] {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walk(full, out);
        } else if (entry.name.endsWith('.ts')) {
            out.push(full);
        }
    }
    return out.sort();
}

function isCommentLine(line: string): boolean {
    const t = line.trim();
    return t.startsWith('*') || t.startsWith('//') || t.startsWith('/*');
}

function stageOf(file: string): string {
    const rel = path.relative(ENGINE_SRC, file).split(path.sep).join('/');
    if (rel.startsWith('syntax/')) {
        return 'parse';
    }
    const m = /^check\/(registry|schema|scope)\.ts$/.exec(rel);
    return m ? m[1] : 'other';
}

/**
 * Catalogue and PYCH- ids the engine reports: string literals in the parser and check
 * sources (outside comments; severity words excluded), with the stage of the file and the
 * severity literal next to them. Parse errors
 * are always errors. Required-field texts the package cites as evidence are reported by
 * the schema check as errors.
 */
function engineUses(catalogue: Map<string, CatalogueEntry>): Map<string, EngineUse> {
    const uses = new Map<string, EngineUse>();
    const known = (id: string) => catalogue.has(id) || id in PYCH_MESSAGES;
    // Diagnostics are produced by the parser (syntax/) and the checks (check/) only.
    const files = [
        ...walk(path.join(ENGINE_SRC, 'syntax')),
        ...walk(path.join(ENGINE_SRC, 'check')),
    ];
    for (const file of files) {
        const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
        const stage = stageOf(file);
        lines.forEach((line, i) => {
            if (isCommentLine(line)) {
                return;
            }
            for (const m of line.matchAll(/'([A-Za-z0-9_-]+)'/g)) {
                const id = m[1];
                if (!known(id) || uses.has(id) || (SEVERITIES as readonly string[]).includes(id)) {
                    continue;
                }
                let severity: Severity | undefined = stage === 'parse' ? 'error' : undefined;
                if (!severity) {
                    const near = lines.slice(Math.max(0, i - 3), i + 2).join('\n');
                    const found = /'(error|warning|information|hint)'/.exec(near);
                    severity = found ? (found[1] as Severity) : 'error';
                }
                uses.set(id, { stage, severity });
            }
        });
    }
    const spec = defaultSpec();
    for (const entry of Object.values(spec.data.schema)) {
        for (const field of Object.values(entry.fields ?? {})) {
            const evidence = field.required_evidence;
            if (!evidence) {
                continue;
            }
            const cited = spec.data.errors.find((e) => e.text === evidence);
            if (cited && !uses.has(cited.id)) {
                uses.set(cited.id, { stage: 'schema', severity: 'error' });
            }
        }
    }
    return uses;
}

function loadPluginCatalogue(): { plugins: Map<string, PluginInfo>; codes: PluginCode[] } {
    const raw = yaml.load(fs.readFileSync(PLUGIN_CATALOGUE, 'utf8')) as {
        plugins: Record<string, PluginInfo>;
        diagnostics: Record<string, { plugin: string; severity: Severity; message: string }>;
    };
    const plugins = new Map(Object.entries(raw.plugins));
    const codes: PluginCode[] = [];
    for (const [code, d] of Object.entries(raw.diagnostics)) {
        const names = d.plugin.split(',').map((p) => p.trim());
        for (const name of names) {
            if (!plugins.has(name)) {
                throw new Error(`data/diagnostics.yaml: ${code} names unknown plug-in '${name}'`);
            }
        }
        if (!SEVERITIES.includes(d.severity)) {
            throw new Error(`data/diagnostics.yaml: ${code} has severity '${d.severity}'`);
        }
        codes.push({ code, plugins: names, severity: d.severity, message: d.message.trim() });
    }
    return { plugins, codes };
}

/** Code literals emitted by the plug-in sources (outside comments and `case` labels). */
function emittedPluginCodes(): Set<string> {
    const files: string[] = [];
    for (const p of PLUGIN_SOURCES) {
        if (fs.statSync(p).isDirectory()) {
            walk(p, files);
        } else {
            files.push(p);
        }
    }
    const codes = new Set<string>();
    for (const file of files) {
        for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
            if (isCommentLine(line) || /^\s*case\s/.test(line)) {
                continue;
            }
            for (const m of line.matchAll(/'((?:CK[0-9]{4})|(?:[A-Z]+-?[0-9]{3}))'/g)) {
                codes.add(m[1]);
            }
        }
    }
    return codes;
}

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

/** A code span that survives backticks and table pipes in the text. */
function code(text: string): string {
    const runs = text.match(/`+/g) ?? [];
    const fence = '`'.repeat(Math.max(0, ...runs.map((r) => r.length)) + 1);
    const pad = text.startsWith('`') || text.endsWith('`') || text.trim() !== text ? ' ' : '';
    return `${fence}${pad}${text.replace(/\|/g, '\\|')}${pad}${fence}`;
}

function cell(text: string): string {
    return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function title(category: string): string {
    return category.replace(/_/g, ' ').replace(/^./, (c) => c.toUpperCase());
}

function pageName(kind: 'catalogue' | 'plugin', name: string): string {
    return `${kind}-${name.replace(/_/g, '-')}.md`;
}

// ---------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------

function cataloguePage(
    category: string,
    entries: CatalogueEntry[],
    uses: Map<string, EngineUse>,
    version: string
): string {
    const reported = entries.filter((e) => uses.has(e.id)).length;
    const lines = [
        GENERATED_NOTE,
        '',
        `# Engine catalogue: ${title(category)}`,
        '',
        `${entries.length} messages of category \`${category}\` in the error catalogue of the CK3 ${version}`,
        `spec package. These are the game's own texts, as \`error.log\` prints them; \`%s\`, \`{}\``,
        `and \`$X$\` mark the values the game fills in. ${reported} of them ${reported === 1 ? 'is' : 'are'} also reported by the`,
        `engine core in the editor (column "pychivalry"); the others are listed so that a line of`,
        '`error.log` can be looked up.',
        '',
        '| Id | Text | Since | pychivalry |',
        '| --- | --- | --- | --- |',
    ];
    for (const e of entries) {
        const use = uses.get(e.id);
        const note = e.note ? ` (${cell(e.note)})` : '';
        const by = use ? `${use.stage}, ${use.severity}` : '';
        lines.push(`| \`${e.id}\` | ${code(e.text)}${note} | ${e.since} | ${by} |`);
    }
    return lines.join('\n') + '\n';
}

function pluginPage(name: string, info: PluginInfo, codes: PluginCode[]): string {
    const lines = [
        GENERATED_NOTE,
        '',
        `# Plug-in: ${name}`,
        '',
        info.description.replace(/\s+/g, ' ').trim(),
        '',
        `Source: \`${info.source}\`.`,
        '',
        '| Code | Severity | Meaning |',
        '| --- | --- | --- |',
    ];
    for (const c of codes) {
        lines.push(`| \`${c.code}\` | ${c.severity} | ${cell(c.message.replace(/\s+/g, ' '))} |`);
    }
    return lines.join('\n') + '\n';
}

function indexPage(
    version: string,
    categories: Array<[string, CatalogueEntry[]]>,
    uses: Map<string, EngineUse>,
    catalogue: Map<string, CatalogueEntry>,
    plugins: Map<string, PluginInfo>,
    byPlugin: Map<string, PluginCode[]>
): string {
    const stageOrder = ['parse', 'registry', 'schema', 'scope', 'other'];
    const engineIds = [...uses.entries()].sort(
        (a, b) =>
            stageOrder.indexOf(a[1].stage) - stageOrder.indexOf(b[1].stage) ||
            a[0].localeCompare(b[0])
    );
    const pluginTotal = new Set([...byPlugin.values()].flat().map((c) => c.code)).size;
    const lines = [
        GENERATED_NOTE,
        '',
        '# Diagnostics reference',
        '',
        'pychivalry reports two kinds of diagnostics.',
        '',
        `- **Engine diagnostics** (source \`ck3-engine\`) come from the engine core. Their id and`,
        `  text are the game's own, taken from the error catalogue of the CK3 ${version} spec`,
        `  package (${catalogue.size} messages), so a diagnostic in the editor reads like the line`,
        `  the game would write to \`error.log\`. A few ids starting with \`PYCH-\` are the`,
        "  engine's own, for conditions the catalogue has no text for.",
        `- **Plug-in diagnostics** (source \`ck3-plugin\`, or \`ck3-localization\` in \`.yml\` files)`,
        `  come from the extension's validators that encode behaviour the spec package does not`,
        `  describe (event timing, style, conventions). ${pluginTotal} codes in ${plugins.size} plug-ins.`,
        '',
        'The engine runs parse, registry, schema and scope checks in that order, then the',
        'plug-ins; see the [validation pipeline](../../developer-guide/architecture/VALIDATION.md).',
        'Per-keyword scope validity ("this trigger is not valid in a title scope") is not checked:',
        'the spec package does not carry it yet.',
        '',
        '## What the engine reports',
        '',
        '| Id | Stage | Severity | Text |',
        '| --- | --- | --- | --- |',
    ];
    for (const [id, use] of engineIds) {
        const text = catalogue.get(id)?.text ?? PYCH_MESSAGES[id];
        lines.push(`| \`${id}\` | ${use.stage} | ${use.severity} | ${code(text)} |`);
    }
    lines.push(
        '',
        'An unknown keyword in a trigger or effect block, or a field unknown to a directory',
        'schema, is reported with the catalogue text the game uses for it; the full catalogue',
        'is below.',
        '',
        '## Plug-ins',
        '',
        '| Page | Codes | What it checks |',
        '| --- | --- | --- |'
    );
    for (const [name, info] of plugins) {
        const codes = byPlugin.get(name) ?? [];
        lines.push(
            `| [${name}](${pageName('plugin', name)}) | ${codes.length} | ${cell(info.description.replace(/\s+/g, ' ').trim())} |`
        );
    }
    lines.push(
        '',
        '## Engine catalogue by category',
        '',
        '| Page | Messages | Reported by the engine |',
        '| --- | --- | --- |'
    );
    for (const [category, entries] of categories) {
        const reported = entries.filter((e) => uses.has(e.id)).length;
        lines.push(
            `| [${title(category)}](${pageName('catalogue', category)}) | ${entries.length} | ${reported} |`
        );
    }
    lines.push(
        '',
        '## Severity',
        '',
        '| Severity | Meaning |',
        '| --- | --- |',
        '| error | The game rejects or misreads the script. |',
        '| warning | Probably wrong; the game accepts it but the result is unlikely to be intended. |',
        '| information | Worth a look; often a convention or a performance note. |',
        '| hint | Style. |'
    );
    return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function generate(): { pages: Map<string, string>; problems: string[] } {
    const spec = defaultSpec();
    const version = spec.version();
    const catalogue = new Map<string, CatalogueEntry>(
        spec.data.errors.map((e) => [e.id, e as CatalogueEntry])
    );
    const uses = engineUses(catalogue);

    const byCategory = new Map<string, CatalogueEntry[]>();
    for (const e of catalogue.values()) {
        const list = byCategory.get(e.category) ?? [];
        list.push(e);
        byCategory.set(e.category, list);
    }
    const categories = [...byCategory.entries()].sort((a, b) => a[0].localeCompare(b[0]));
    for (const [, entries] of categories) {
        entries.sort((a, b) => a.id.localeCompare(b.id));
    }

    const { plugins, codes } = loadPluginCatalogue();
    const byPlugin = new Map<string, PluginCode[]>();
    for (const c of codes) {
        for (const p of c.plugins) {
            const list = byPlugin.get(p) ?? [];
            list.push(c);
            byPlugin.set(p, list);
        }
    }
    for (const list of byPlugin.values()) {
        list.sort((a, b) => a.code.localeCompare(b.code));
    }

    const problems: string[] = [];
    const emitted = emittedPluginCodes();
    const listed = new Set(codes.map((c) => c.code));
    for (const c of [...emitted].sort()) {
        if (!listed.has(c)) {
            problems.push(`a plug-in emits ${c}, which data/diagnostics.yaml does not list`);
        }
    }
    for (const c of [...listed].sort()) {
        if (!emitted.has(c)) {
            problems.push(`data/diagnostics.yaml lists ${c}, which no plug-in emits`);
        }
    }

    const pages = new Map<string, string>();
    pages.set('README.md', indexPage(version, categories, uses, catalogue, plugins, byPlugin));
    for (const [category, entries] of categories) {
        pages.set(pageName('catalogue', category), cataloguePage(category, entries, uses, version));
    }
    for (const [name, info] of plugins) {
        pages.set(pageName('plugin', name), pluginPage(name, info, byPlugin.get(name) ?? []));
    }
    return { pages, problems };
}

function main(): void {
    const check = process.argv.includes('--check');
    const { pages, problems } = generate();
    if (check) {
        const existing = fs.existsSync(OUT_DIR) ? fs.readdirSync(OUT_DIR).sort() : [];
        for (const name of existing) {
            if (!pages.has(name)) {
                problems.push(`${name} is not a generated page (delete it or regenerate)`);
            }
        }
        for (const [name, text] of pages) {
            const file = path.join(OUT_DIR, name);
            if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text) {
                problems.push(`${name} is out of date (run npm run docs:diagnostics)`);
            }
        }
        for (const p of problems) {
            process.stderr.write(`gen-diagnostics-docs: ${p}\n`);
        }
        if (problems.length > 0) {
            process.exit(1);
        }
        process.stdout.write(`gen-diagnostics-docs: ${pages.size} pages up to date\n`);
        return;
    }
    if (problems.length > 0) {
        for (const p of problems) {
            process.stderr.write(`gen-diagnostics-docs: ${p}\n`);
        }
        process.exit(1);
    }
    fs.mkdirSync(OUT_DIR, { recursive: true });
    for (const name of fs.readdirSync(OUT_DIR)) {
        if (!pages.has(name)) {
            fs.rmSync(path.join(OUT_DIR, name));
        }
    }
    for (const [name, text] of pages) {
        fs.writeFileSync(path.join(OUT_DIR, name), text);
    }
    process.stdout.write(`gen-diagnostics-docs: wrote ${pages.size} pages to ${OUT_DIR}\n`);
}

main();
